import { Alert, Batch, Device, Shipment } from './models';

/** Fixed reference "now" so relative times in the dummy data stay sensible. */
export const NOW = Date.now();
const HOUR = 3_600_000;
const DAY = 24 * HOUR;
const iso = (offsetMs: number) => new Date(NOW + offsetMs).toISOString();

// ---------------------------------------------------------------------------
// DUMMY DATA — used only when environment.useDummyData is true. See
// core/services/batch.service.ts, alert.service.ts, shipment.service.ts and
// device.service.ts for how each one maps the real .NET API's DTOs instead.
// ---------------------------------------------------------------------------

export const MOCK_BATCHES: Batch[] = [
  {
    id: 'b1',
    batchNumber: 'BX-2026-0417-A',
    drugName: 'Pfizer-BioNTech COVID-19 Vaccine',
    manufacturer: 'BioNTech Manufacturing GmbH',
    status: 'quarantined',
    minTempC: 2,
    maxTempC: 8,
    quantity: 4800,
    unit: 'vials',
    manufacturedAt: iso(-26 * DAY),
    expiresAt: iso(94 * DAY),
    deviceId: 'SNS-A41-0092',
    lastReading: {
      id: 'r1',
      batchId: 'b1',
      deviceId: 'SNS-A41-0092',
      temperatureC: 11.4,
      humidityPct: 61,
      lat: 52.3702,
      lng: 4.8952,
      recordedAt: iso(-6 * HOUR),
    },
    location: { lat: 52.3702, lng: 4.8952, label: 'Amsterdam Distribution Hub' },
  },
  {
    id: 'b2',
    batchNumber: 'IG-2026-1183-C',
    drugName: 'Insulin Glargine 100 IU/mL',
    manufacturer: 'Sanofi-Aventis Deutschland',
    status: 'in_transit',
    minTempC: 2,
    maxTempC: 8,
    quantity: 1200,
    unit: 'pens',
    manufacturedAt: iso(-41 * DAY),
    expiresAt: iso(22 * DAY),
    deviceId: 'SNS-C12-4477',
    lastReading: {
      id: 'r2',
      batchId: 'b2',
      deviceId: 'SNS-C12-4477',
      temperatureC: 7.2,
      humidityPct: 55,
      lat: 50.1109,
      lng: 8.6821,
      recordedAt: iso(-18 * 60_000),
    },
    location: { lat: 50.1109, lng: 8.6821, label: 'En route · A3 near Frankfurt' },
  },
  {
    id: 'b3',
    batchNumber: 'HB-2026-0044-B',
    drugName: 'Hepatitis B Immune Globulin',
    manufacturer: 'Grifols Biologicals',
    status: 'in_transit',
    minTempC: 2,
    maxTempC: 8,
    quantity: 640,
    unit: 'syringes',
    manufacturedAt: iso(-12 * DAY),
    expiresAt: iso(310 * DAY),
    deviceId: 'SNS-B77-1130',
    lastReading: {
      id: 'r3',
      batchId: 'b3',
      deviceId: 'SNS-B77-1130',
      temperatureC: 5.1,
      humidityPct: 48,
      lat: 48.8566,
      lng: 2.3522,
      recordedAt: iso(-4 * 60_000),
    },
    location: { lat: 48.8566, lng: 2.3522, label: 'En route · Paris ring road' },
  },
  {
    id: 'b4',
    batchNumber: 'AZ-2026-0290-D',
    drugName: 'AstraZeneca Cold-Chain Adjuvant Kit',
    manufacturer: 'AstraZeneca AB',
    status: 'active',
    minTempC: 2,
    maxTempC: 8,
    quantity: 3100,
    unit: 'vials',
    manufacturedAt: iso(-8 * DAY),
    expiresAt: iso(178 * DAY),
    deviceId: 'SNS-D19-2201',
    lastReading: {
      id: 'r4',
      batchId: 'b4',
      deviceId: 'SNS-D19-2201',
      temperatureC: 4.6,
      humidityPct: 52,
      lat: 59.3293,
      lng: 18.0686,
      recordedAt: iso(-9 * 60_000),
    },
    location: { lat: 59.3293, lng: 18.0686, label: 'Stockholm Cold Storage Facility 2' },
  },
  {
    id: 'b5',
    batchNumber: 'MG-2026-0771-E',
    drugName: 'Somatropin Growth Hormone Injection',
    manufacturer: 'Novo Nordisk A/S',
    status: 'active',
    minTempC: 2,
    maxTempC: 8,
    quantity: 900,
    unit: 'cartridges',
    manufacturedAt: iso(-3 * DAY),
    expiresAt: iso(365 * DAY),
    deviceId: 'SNS-E88-3390',
    lastReading: {
      id: 'r5',
      batchId: 'b5',
      deviceId: 'SNS-E88-3390',
      temperatureC: 3.8,
      humidityPct: 50,
      lat: 55.6761,
      lng: 12.5683,
      recordedAt: iso(-2 * 60_000),
    },
    location: { lat: 55.6761, lng: 12.5683, label: 'Copenhagen Warehouse North' },
  },
  {
    id: 'b6',
    batchNumber: 'RB-2025-9981-F',
    drugName: 'Rabies Immune Globulin (Human)',
    manufacturer: 'Grifols Biologicals',
    status: 'delivered',
    minTempC: 2,
    maxTempC: 8,
    quantity: 210,
    unit: 'vials',
    manufacturedAt: iso(-70 * DAY),
    expiresAt: iso(400 * DAY),
    deviceId: 'SNS-F51-7743',
    lastReading: {
      id: 'r6',
      batchId: 'b6',
      deviceId: 'SNS-F51-7743',
      temperatureC: 4.1,
      humidityPct: 47,
      lat: 48.1351,
      lng: 11.582,
      recordedAt: iso(-5 * DAY),
    },
    location: { lat: 48.1351, lng: 11.582, label: 'Munich Regional Pharmacy' },
  },
  {
    id: 'b7',
    batchNumber: 'PL-2025-4432-G',
    drugName: 'Platelet Concentrate Unit',
    manufacturer: 'Red Cross Blood Services',
    status: 'recalled',
    minTempC: 20,
    maxTempC: 24,
    quantity: 48,
    unit: 'units',
    manufacturedAt: iso(-30 * DAY),
    expiresAt: iso(-2 * DAY),
    deviceId: 'SNS-G22-5561',
    lastReading: {
      id: 'r7',
      batchId: 'b7',
      deviceId: 'SNS-G22-5561',
      temperatureC: 29.8,
      humidityPct: 66,
      lat: 50.8503,
      lng: 4.3517,
      recordedAt: iso(-9 * DAY),
    },
    location: { lat: 50.8503, lng: 4.3517, label: 'Brussels Central Blood Bank' },
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'a1',
    batchId: 'b1',
    batchNumber: 'BX-2026-0417-A',
    drugName: 'Pfizer-BioNTech COVID-19 Vaccine',
    severity: 'critical',
    message:
      'CRITICAL: Batch BX-2026-0417-A recorded 11.4°C — outside safe range [2.0°C to 8.0°C]. Batch quarantined.',
    triggeredAt: iso(-6 * HOUR),
    resolvedAt: null,
    resolvedBy: null,
  },
  {
    id: 'a2',
    batchId: 'b2',
    batchNumber: 'IG-2026-1183-C',
    drugName: 'Insulin Glargine 100 IU/mL',
    severity: 'warning',
    message: 'WARNING: Batch IG-2026-1183-C recorded 7.2°C — approaching the edge of its safe range.',
    triggeredAt: iso(-40 * 60_000),
    resolvedAt: null,
    resolvedBy: null,
  },
  {
    id: 'a3',
    batchId: 'b7',
    batchNumber: 'PL-2025-4432-G',
    drugName: 'Platelet Concentrate Unit',
    severity: 'critical',
    message:
      'CRITICAL: Batch PL-2025-4432-G recorded 29.8°C — outside safe range [20.0°C to 24.0°C]. Batch quarantined.',
    triggeredAt: iso(-9 * DAY),
    resolvedAt: iso(-9 * DAY + 3 * HOUR),
    resolvedBy: 'Mona Ostrowski',
  },
];

export const MOCK_SHIPMENTS: Shipment[] = [
  {
    id: 's1',
    batchId: 'b2',
    origin: 'Sanofi Frankfurt Plant',
    destination: 'Berlin Central Pharmacy Depot',
    courier: 'ColdLine Logistics',
    status: 'in_transit',
    departedAt: iso(-3 * HOUR),
    arrivedAt: null,
  },
  {
    id: 's2',
    batchId: 'b3',
    origin: 'Grifols Paris Facility',
    destination: 'Lyon University Hospital',
    courier: 'MedTrans Express',
    status: 'in_transit',
    departedAt: iso(-90 * 60_000),
    arrivedAt: null,
  },
  {
    id: 's3',
    batchId: 'b6',
    origin: 'Grifols Munich Facility',
    destination: 'Munich Regional Pharmacy',
    courier: 'ColdLine Logistics',
    status: 'delivered',
    departedAt: iso(-6 * DAY),
    arrivedAt: iso(-5 * DAY),
  },
];

export const MOCK_DEVICES: Device[] = [
  {
    id: 'SNS-A41-0092',
    deviceCode: 'SNS-A41-0092',
    model: 'ColdTrace T4',
    assignedBatchId: 'b1',
    assignedBatchNumber: 'BX-2026-0417-A',
    lastSeenAt: iso(-6 * HOUR),
    batteryPct: 41,
    signalPct: 62,
    status: 'online',
  },
  {
    id: 'SNS-C12-4477',
    deviceCode: 'SNS-C12-4477',
    model: 'ColdTrace T4',
    assignedBatchId: 'b2',
    assignedBatchNumber: 'IG-2026-1183-C',
    lastSeenAt: iso(-18 * 60_000),
    batteryPct: 78,
    signalPct: 91,
    status: 'online',
  },
  {
    id: 'SNS-B77-1130',
    deviceCode: 'SNS-B77-1130',
    model: 'ColdTrace T4',
    assignedBatchId: 'b3',
    assignedBatchNumber: 'HB-2026-0044-B',
    lastSeenAt: iso(-4 * 60_000),
    batteryPct: 88,
    signalPct: 95,
    status: 'online',
  },
  {
    id: 'SNS-H63-9987',
    deviceCode: 'SNS-H63-9987',
    model: 'ColdTrace T3',
    assignedBatchId: null,
    assignedBatchNumber: null,
    lastSeenAt: iso(-52 * 60_000),
    batteryPct: 19,
    signalPct: 40,
    status: 'stale',
  },
  {
    id: 'SNS-J04-1120',
    deviceCode: 'SNS-J04-1120',
    model: 'ColdTrace T3',
    assignedBatchId: null,
    assignedBatchNumber: null,
    lastSeenAt: iso(-3 * DAY),
    batteryPct: 4,
    signalPct: 0,
    status: 'offline',
  },
];
