using System.Text.Json;

namespace MedGuard.Contracts.Devices;

/// <summary>
/// One temperature reading as a device publishes it. This is a wire contract
/// shared by every service in the pipeline, so change it additively only
/// (new optional fields), because old devices in the field keep sending the old shape.
/// </summary>
/// <param name="MessageId">
/// Generated by the device, once per reading. MQTT QoS 1 and Kafka are both
/// at-least-once, so the same reading WILL arrive twice sometimes; consumers
/// use this id to drop the duplicate.
/// </param>
/// <param name="RecordedAtUtc">
/// When the sensor took the reading, not when the server received it. A device
/// that was offline for an hour flushes an hour of old readings on reconnect,
/// and they must be evaluated at the time they actually happened.
/// </param>
public record DeviceTelemetry(
    Guid MessageId,
    string DeviceCode,
    Guid BatchId,
    decimal TemperatureC,
    decimal? HumidityPercent,
    double? Latitude,
    double? Longitude,
    DateTime RecordedAtUtc);

public record DeviceHeartbeat(
    string DeviceCode,
    int BatteryPercent,
    int SignalPercent,
    DateTime SentAtUtc);

/// <summary>Payloads of the retained <c>.../status</c> topic.</summary>
public static class DeviceConnectionStatus
{
    public const string Online = "online";
    public const string Offline = "offline";
}

public static class ContractJson
{
    /// <summary>camelCase and case-insensitive: the same conventions as the HTTP API.</summary>
    public static readonly JsonSerializerOptions Options = new(JsonSerializerDefaults.Web);
}
